export { presetEntriesOptions } from './src/presetEntriesOptions'
export { presetObjectOptions } from './src/presetObjectOptions'
export { presetVectorOptions } from './src/presetVectorOptions'
export { presetMatrixOptions } from './src/presetMatrixOptions'
export { presetCrostabOptions } from './src/presetCrostabOptions'
export { presetTableOptions } from './src/presetTableOptions'
export { presetSamplesOptions } from './src/presetSamplesOptions'
export { quoteString, pipeQuote } from './src/quoteString'
export { joinLines, liner } from './src/joinLines'
