export { toFullAngleWoAnsi }                from './src/toFullAngleWoAnsi'
export { hasChn, toFullAngle, toHalfAngle } from './src/fullAngle'
export { indexNonTab, afterNonTab }         from './src/tab'
export { narrow, narrowExclude }            from './src/narrow'
export { wL, tag }                          from './src/brief'
export { stringValue }                      from './src/stringValue'
