export { camelToSnake as camelToLowerDashed, snakeToCamel as dashedToCamel } from '@spare/phrasing'
export { hasChn, toFullAngle, toHalfAngle } from './src/fullAngle'
export { padStartAnsi, padEndAnsi } from './src/pad'
export { indexNonTab, afterNonTab } from './src/tab'
export { narrow, narrowExclude } from './src/narrow'
export { wL, tag } from './src/brief'
