export const SP = ' '
export const TB = '  '
export const CO = ','
export const CR = '\r'
export const LF = '\n'
export const RN = '\r\n'
export const DASH = '-'
export const ELLIP = '...'
export const AEU = '(Ø)'

