export { logger, logNeL } from './src/logger'
export { deco, Deco, delogger, delogNeL }           from '@spare/deco'
export { deco as decoString, Deco as DecoString }   from '@spare/deco-string'
export { deco as decoVector, Deco as DecoVector }   from '@spare/deco-vector'
export { deco as decoEntries, Deco as DecoEntries } from '@spare/deco-entries'
export { deco as decoObject, Deco as DecoObject }   from '@spare/deco-object'
export { deco as decoMatrix, Deco as DecoMatrix }   from '@spare/deco-matrix'
export { deco as decoSamples, Deco as DecoSamples } from 'packages/interop/deco-samples'
export { deco as decoTable, Deco as DecoTable }     from 'packages/interop/deco-table'
export { deco as decoCrostab, Deco as DecoCrostab } from 'packages/interop/deco-crostab'
export { decoFunc, DecoFunc }                       from '@spare/deco-func'
export { decoPale, DecoPale }                       from '@spare/deco-pale'
export { decoFlat, DecoFlat }                       from '@spare/deco-flat'
export { Says, says, ros }                          from '@spare/says'
export { Xr, xr }                                   from '@spare/xr'


