export { logger, logNeL }              from './src/logger.js'
export { deco, Deco }                  from '@spare/deco'
export { decoString, DecoString }      from '@spare/deco-string'
export { decoVector, DecoVector }      from '@spare/deco-vector'
export { decoEntries, DecoEntries }    from '@spare/deco-entries'
export { decoObject, DecoObject }      from '@spare/deco-object'
export { decoMatrix, DecoMatrix }      from '@spare/deco-matrix'
export { decoSamples }                 from '@spare/deco-samples'
export { decoTable, DecoTable }        from '@spare/deco-table'
export { decoCrostab, DecoCrostab }    from '@spare/deco-crostab'
export { decoFunc, DecoFunc }          from '@spare/deco-func'
export { decoPale, DecoPale }          from '@spare/deco-pale'
export { decoFlat, DecoFlat }          from '@spare/deco-flat'
export { Xr, xr, ros, cr, x, $, says } from '@spare/xr'


